### PR TITLE
Make flask assistant work in python 2.7

### PR DESCRIPTION
**Pull request by fameoflight**

### CODE REVIEW

**Comment by treethought** [comment]
awesome, thanks @fameoflight! have you tested that it still works for python 3?

**Comment by fameoflight** [comment]
@treethought do you mind checking for python 3 I have tested this on python 2.7 

Also added one more commit to be able to use both flask ask and assistant in the same project. Flask require each view function have unique name so the change.

**Comment by treethought** [comment]
seems to work with python 3, thanks. 

With the flask-ask commit: I think I'll merge this in as it doesn't change anything within flask-assistant.

 But I am curious does this work if both the flask-ask and flask-assistant apps are registered under the same route ('/')?  Or did you just set your ASK skill and flask-assistant API.AI webhook to separate URLs such as `example.com/ask` and `example.com/assistant`?
 
Because I'm unsure if the same route can be mapped to two separate view functions.

**Comment by fameoflight** [comment]
You have to map them to different end points.

**Pull request merged**
